DEF PLAN_ADDR 0000;
DEF ID_ADDR 7FC0;
DEF SREC_ADDR 7FE0;
DEF HADDR1 0060;
DEF HADDR2 1000;
DEF HADDR3 1800;

#*reboot;
ini f;

#*initializing it now;
#* ;

#*write plan;
eew PLAN_ADDR plan.bin;

#*write id;
eew ID_ADDR id.bin;

#*write sreconf;
eew SREC_ADDR sreconf_nw.bin;

#*write header;
eew HADDR1 hrec.bin;
eew HADDR2 hrec.bin;
eew HADDR3 hrec.bin;

#*reboot;
ini f;

pau 400;

#*erase nand;
nae;

sts f;

bye;

quit;